/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class TrackerTrackee {
    getFieldTypeMap() {
        let fieldTypeMap = new Map();
        fieldTypeMap.set('id', 'String');
        fieldTypeMap.set('trackerId', 'String');
        fieldTypeMap.set('trackeeId', 'String');
        return fieldTypeMap;
    }

    getClassName() {
        return 'TrackerTrackee';
    }

    getPrimaryKeyList() {
        let primaryKeyList = [];
        primaryKeyList.push('id');
        return primaryKeyList;
    }

    getIndexList() {
        let indexList = [];
        return indexList;
    }

    getEncryptedFieldList() {
        let encryptedFieldList = [];
        return encryptedFieldList;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setTrackerId(trackerId) {
        this.trackerId = trackerId;
    }

    getTrackerId() {
        return this.trackerId;
    }

    setTrackeeId(trackeeId) {
        this.trackeeId = trackeeId;
    }

    getTrackeeId() {
        return this.trackeeId;
    }
}

module.exports = {TrackerTrackee}