/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class User {
    getFieldTypeMap() {
        let fieldTypeMap = new Map();
        fieldTypeMap.set('phoneId', 'String');
        fieldTypeMap.set('givenName', 'String');
        fieldTypeMap.set('familyName', 'String');
        fieldTypeMap.set('isTracker', 'Boolean');
        return fieldTypeMap;
    }

    getClassName() {
        return 'User';
    }

    getPrimaryKeyList() {
        let primaryKeyList = [];
        primaryKeyList.push('phoneId');
        return primaryKeyList;
    }

    getIndexList() {
        let indexList = [];
        return indexList;
    }

    getEncryptedFieldList() {
        let encryptedFieldList = [];
        return encryptedFieldList;
    }

    setPhoneId(phoneId) {
        this.phoneId = phoneId;
    }

    getPhoneId() {
        return this.phoneId;
    }

    setGivenName(givenName) {
        this.givenName = givenName;
    }

    getGivenName() {
        return this.givenName;
    }

    setFamilyName(familyName) {
        this.familyName = familyName;
    }

    getFamilyName() {
        return this.familyName;
    }

    setIsTracker(isTracker) {
        this.isTracker = isTracker;
    }

    getIsTracker() {
        return this.isTracker;
    }
}

module.exports = {User}